import { NextRequest, NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const PROJECT_ROOT = path.join(os.homedir(), "shopify-autotest");
const TESTS_DIR = path.join(PROJECT_ROOT, "tests");

interface TestFileInfo {
  /** Relative path from project root */
  file: string;
  /** App folder (avada-plaza, seo, blogs) */
  app: string;
  /** File name without extension */
  name: string;
  /** Number of test cases */
  testCount: number;
  /** Has @smoke tag */
  hasSmoke: boolean;
  /** Last modified date */
  modifiedAt: string;
  /** File size bytes */
  size: number;
  /** Generated by AI pipeline? */
  isGenerated: boolean;
  /** Metadata from @generated header */
  meta: {
    taskId?: string;
    taskTitle?: string;
    branch?: string;
    feature?: string;
    generatedAt?: string;
  };
}

function scanTestFiles(): TestFileInfo[] {
  const results: TestFileInfo[] = [];

  if (!fs.existsSync(TESTS_DIR)) return results;

  const appDirs = fs.readdirSync(TESTS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith("_")); // skip _archive etc.

  for (const dir of appDirs) {
    const appDir = path.join(TESTS_DIR, dir.name);
    const specFiles = fs.readdirSync(appDir)
      .filter(f => f.endsWith(".spec.ts"));

    for (const file of specFiles) {
      const filePath = path.join(appDir, file);
      const content = fs.readFileSync(filePath, "utf-8");
      const stat = fs.statSync(filePath);
      const relPath = path.relative(PROJECT_ROOT, filePath);

      // Count test cases
      const testMatches = content.match(/\btest\s*\(/g) || [];
      const testCount = testMatches.length;

      // Check @smoke
      const hasSmoke = content.includes("@smoke");

      // Parse metadata header
      const meta: TestFileInfo["meta"] = {};
      const isGenerated = content.includes("@generated");

      if (isGenerated) {
        const taskIdMatch = content.match(/@taskId\s+(.+)/);
        const taskMatch = content.match(/@task\s+(.+)/);
        const branchMatch = content.match(/@branch\s+(.+)/);
        const featureMatch = content.match(/@feature\s+(.+)/);
        const generatedMatch = content.match(/@generated\s+AI Pipeline\s*—\s*(.+)/);

        if (taskIdMatch) meta.taskId = taskIdMatch[1].trim();
        if (taskMatch) meta.taskTitle = taskMatch[1].trim();
        if (branchMatch) meta.branch = branchMatch[1].trim();
        if (featureMatch) meta.feature = featureMatch[1].trim();
        if (generatedMatch) meta.generatedAt = generatedMatch[1].trim();
      }

      results.push({
        file: relPath,
        app: dir.name,
        name: file.replace(".spec.ts", ""),
        testCount,
        hasSmoke,
        modifiedAt: stat.mtime.toISOString(),
        size: stat.size,
        isGenerated,
        meta,
      });
    }
  }

  // Sort: newest first
  results.sort((a, b) => new Date(b.modifiedAt).getTime() - new Date(a.modifiedAt).getTime());

  return results;
}

export async function GET() {
  const files = scanTestFiles();

  return NextResponse.json({
    total: files.length,
    generated: files.filter(f => f.isGenerated).length,
    manual: files.filter(f => !f.isGenerated).length,
    files,
  });
}

/**
 * DELETE /api/smart/test-catalog
 * Body: { files: string[] }  — relative paths from project root
 *
 * Moves files to _archive instead of hard-delete for safety.
 * Returns: { deleted: string[], errors: string[] }
 */
export async function DELETE(request: NextRequest) {
  let body: { files?: string[] };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { files = [] } = body;

  if (!Array.isArray(files) || files.length === 0) {
    return NextResponse.json({ error: "files array required" }, { status: 400 });
  }

  const deleted: string[] = [];
  const errors: string[] = [];

  for (const relPath of files) {
    // Security: only allow paths inside tests/ directory, no traversal
    const absPath = path.resolve(PROJECT_ROOT, relPath);
    if (!absPath.startsWith(TESTS_DIR) || !absPath.endsWith(".spec.ts")) {
      errors.push(`${relPath}: path not allowed`);
      continue;
    }

    if (!fs.existsSync(absPath)) {
      errors.push(`${relPath}: file not found`);
      continue;
    }

    try {
      // Move to _archive instead of hard-delete
      const appDir = path.dirname(absPath);
      const archiveDir = path.join(appDir, "_archive");
      fs.mkdirSync(archiveDir, { recursive: true });

      const fileName = path.basename(absPath);
      const archivePath = path.join(archiveDir, fileName);

      // If archive already has this file, add timestamp suffix
      const finalArchivePath = fs.existsSync(archivePath)
        ? path.join(archiveDir, fileName.replace(".spec.ts", `_${Date.now()}.spec.ts`))
        : archivePath;

      fs.renameSync(absPath, finalArchivePath);
      deleted.push(relPath);
    } catch (err) {
      errors.push(`${relPath}: ${String(err)}`);
    }
  }

  return NextResponse.json({ deleted, errors });
}
