#!/usr/bin/env node
/**
 * Source Code Scanner
 *
 * Tự động extract từ source code app:
 * - data-testid attributes
 * - Toast messages (từ locale/translations)
 * - Button/link text
 * - Route paths
 *
 * Ghi ra skills/shopify-test-gen/references/app-context/[app].md
 *
 * Usage:
 *   npm run scan-source -- --app avadaPlaza --src /path/to/app/src
 *   npm run scan-source -- --app avadaPlaza --src /path/to/app/src --locale src/locale/translations/origin.json
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CONTEXT_DIR = path.join(ROOT, 'skills/shopify-test-gen/references/app-context');

// ── Arg parsing ─────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const getArg = (flag) => {
  const idx = args.indexOf(flag);
  return idx >= 0 ? args[idx + 1] : null;
};

const appKey = getArg('--app') || 'avadaPlaza';
const srcDir = getArg('--src');
const localeFile = getArg('--locale');

// ── Scanners ─────────────────────────────────────────────────────────────────

/**
 * Extract tất cả data-testid values từ source files.
 */
function scanTestIds(dir) {
  const testIds = new Set();
  const pattern = /data-testid=["'`]([^"'`]+)["'`]/g;

  const walk = (d) => {
    if (!fs.existsSync(d)) return;
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (['node_modules', '.git', 'dist', 'build'].includes(entry.name)) continue;
        walk(path.join(d, entry.name));
      } else if (/\.(jsx?|tsx?)$/.test(entry.name)) {
        const content = fs.readFileSync(path.join(d, entry.name), 'utf-8');
        let match;
        while ((match = pattern.exec(content)) !== null) {
          testIds.add(match[1]);
        }
        pattern.lastIndex = 0;
      }
    }
  };

  walk(dir);
  return [...testIds].sort();
}

/**
 * Extract route paths từ source files.
 */
function scanRoutes(dir) {
  const routes = new Set();
  const patterns = [
    /path=["'`](\/[^"'`]*)["'`]/g,
    /to=["'`](\/[^"'`]*)["'`]/g,
    /navigate\(["'`](\/[^"'`]*)["'`]/g,
  ];

  const walk = (d) => {
    if (!fs.existsSync(d)) return;
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (['node_modules', '.git', 'dist', 'build'].includes(entry.name)) continue;
        walk(path.join(d, entry.name));
      } else if (/\.(jsx?|tsx?)$/.test(entry.name)) {
        const content = fs.readFileSync(path.join(d, entry.name), 'utf-8');
        for (const pat of patterns) {
          let match;
          while ((match = pat.exec(content)) !== null) {
            const route = match[1];
            if (route.length > 1 && !route.includes('{') && !route.includes('$')) {
              routes.add(route);
            }
          }
          pat.lastIndex = 0;
        }
      }
    }
  };

  walk(dir);
  return [...routes].sort();
}

/**
 * Flatten locale JSON thành list string values (leaf nodes).
 */
function flattenLocale(obj, prefix = '') {
  const results = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') {
      results.push({ key: fullKey, value });
    } else if (typeof value === 'object' && value !== null) {
      results.push(...flattenLocale(value, fullKey));
    }
  }
  return results;
}

/**
 * Extract toast/success/error messages từ locale file.
 */
function scanLocale(localeFilePath) {
  if (!fs.existsSync(localeFilePath)) return { toasts: [], errors: [], buttons: [] };

  const data = JSON.parse(fs.readFileSync(localeFilePath, 'utf-8'));
  const flat = flattenLocale(data);

  const toasts = flat.filter(({ key, value }) =>
    /toast|success|done|finish|complet|saved|updated/i.test(key) ||
    /toast|success|done|finish/i.test(value)
  ).map(({ value }) => value).filter(v => v.length < 100);

  const errors = flat.filter(({ key, value }) =>
    /error|fail|invalid|wrong|warning/i.test(key)
  ).map(({ value }) => value).filter(v => v.length < 100);

  const buttons = flat.filter(({ key, value }) =>
    /button|btn|action|label|cta/i.test(key)
  ).map(({ value }) => value).filter(v => v.length < 50 && v.length > 1);

  return {
    toasts: [...new Set(toasts)],
    errors: [...new Set(errors)],
    buttons: [...new Set(buttons)],
  };
}

// ── Generate markdown ────────────────────────────────────────────────────────

function generateMarkdown(appKey, { testIds, routes, toasts, errors, buttons }) {
  const lines = [
    `# ${appKey} — Auto-scanned App Context`,
    ``,
    `> Generated by \`npm run scan-source\` on ${new Date().toISOString().split('T')[0]}.`,
    `> Review and supplement manually as needed.`,
    ``,
  ];

  if (routes.length) {
    lines.push(`## Routes`);
    routes.forEach(r => lines.push(`- \`${r}\``));
    lines.push('');
  }

  if (testIds.length) {
    lines.push(`## data-testid (use getByTestId)`);
    lines.push('```');
    testIds.forEach(id => lines.push(id));
    lines.push('```');
    lines.push('');
  }

  if (toasts.length) {
    lines.push(`## Toast / Success Messages (exact text for assertions)`);
    lines.push('```');
    toasts.forEach(t => lines.push(`"${t}"`));
    lines.push('```');
    lines.push('');
  }

  if (errors.length) {
    lines.push(`## Error / Warning Messages`);
    lines.push('```');
    errors.slice(0, 20).forEach(e => lines.push(`"${e}"`));
    lines.push('```');
    lines.push('');
  }

  if (buttons.length) {
    lines.push(`## Button / Action Labels`);
    lines.push('```');
    [...new Set(buttons)].slice(0, 30).forEach(b => lines.push(`"${b}"`));
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  if (!srcDir) {
    console.error('');
    console.error('Usage:');
    console.error('  npm run scan-source -- --app avadaPlaza --src /path/to/app/src');
    console.error('  npm run scan-source -- --app avadaPlaza --src /path/to/app/src --locale /path/to/origin.json');
    console.error('');
    process.exit(1);
  }

  console.log(`\n🔍 Scanning source: ${srcDir}`);

  const testIds = srcDir ? scanTestIds(srcDir) : [];
  const routes = srcDir ? scanRoutes(srcDir) : [];

  const localeFilePath = localeFile ||
    path.join(srcDir, 'locale/translations/origin.json');
  const { toasts, errors, buttons } = scanLocale(localeFilePath);

  console.log(`  ✅ test-ids: ${testIds.length}`);
  console.log(`  ✅ routes: ${routes.length}`);
  console.log(`  ✅ toasts: ${toasts.length}`);
  console.log(`  ✅ errors: ${errors.length}`);
  console.log(`  ✅ button labels: ${buttons.length}`);

  const md = generateMarkdown(appKey, { testIds, routes, toasts, errors, buttons });

  // Lưu vào scanned file riêng (không overwrite curated file)
  const outFile = path.join(CONTEXT_DIR, `${appKey}.scanned.md`);
  fs.mkdirSync(CONTEXT_DIR, { recursive: true });
  fs.writeFileSync(outFile, md);

  console.log(`\n✅ Saved: ${path.relative(ROOT, outFile)}`);
  console.log(`\n💡 Review file trên và merge vào ${appKey}.md nếu cần.`);
  console.log(`   File .scanned.md sẽ được inject tự động vào test:generate.\n`);
}

main();
